title: Shane O. Chandler Seasoned IT Professional 
description: Over 15 years of experience in IT, currently transitioning to a career in Cyber Security.<span id="cursor">_</span>
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker 


var i = 0;
var txt = 'Your text goes here...'; /* The text you want to display */
var speed = 50; /* The speed/duration of the effect in milliseconds */

function typeWriter() {
  if (i < txt.length) {
    document.getElementById("demo").innerHTML += txt.charAt(i);
    i++;
    setTimeout(typeWriter, speed);
  }
}

typeWriter();




