title: Shane O. Chandler Experienced IT Professional 
description: Over 15 years of experience in IT, currently transitioning to a career in Cyber Security.
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
site_text: "This is my selected text"

